apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: litter
  name: litter
spec:
  type: NodePort # Using this to connect loadBalancer to in CSCloud
  ports:
    - name: "litter-port"
      port: 3000
      targetPort: 8080
  selector:
    deployment.name: litter
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: litter
  template:
    metadata:
      labels:
        deployment.name: litter
    spec:
      containers:
      - name: litter
        image: gitlab.lnu.se:5050/2dv013/student/team-5-burmese/2DV013-Cloud-Native-Assignment-3-Frontend/litter-frontend
        env:
        - name: SESSION_NAME
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: name
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: secret
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred # Secret set as a secret in the cluster